name: 'Terraform'

on:
  push:
    paths:
      - '09-demo/gitops/app/**'
      - '.github/workflows/terraform.yml'
    branches: [ "main" ]
  pull_request:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-20.04

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ vars.AWS_ROLE }}
        role-session-name: github-terraform-training-repo
        aws-region: ${{ vars.AWS_REGION }}

    - name: AWS Check
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
        aws s3 ls

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: true
        terraform_version: 1.4.5


  # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: |
        cd 09-demo/gitops/app
        terraform init

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: |
        cd 09-demo/gitops/app
        TF_LOG=debug terraform plan -input=false
        terraform apply -auto-approve 

      # On push to "main", build or change infrastructure according to Terraform configuration files
      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
    - name: Terraform Apply
      if: github.ref == 'refs/heads/"main"' && github.event_name == 'push'
      run: |
        cd 09-demo/gitops/app
        terraform apply -auto-approve -input=false
